issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - goconst
        - errcheck
        - staticcheck
    - path: compress/zlib/(.+).go
      linters:
        - errcheck
    - path: compress/gzip/(.+).go
      linters:
        - errcheck
